#pragma once
#include <iostream>
#include <fstream>
#include <random>

template<typename T>
void Print(std::ofstream &fout, T first)
{
    fout << first << std::endl;
}

template<typename ... Args, typename T>
void Print(std::ofstream &fout, T first, Args... args)
{
    fout << first << " ";
    Print(fout, args...);
}

void GenerateData()
{
    std::ofstream fout("data.txt");
    std::random_device rd;
    for (int i = 0; i < 100000; ++i)
    {
        Print(fout,
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max(),
            (float)(rd()) / rd.max());
    }
    fout.close();
}
